DROP PROCEDURE IF EXISTS mugenjo.`PKG_MANAGEUSER.PRC_GETUSERDETAILS`;
CREATE PROCEDURE mugenjo.`PKG_MANAGEUSER.PRC_GETUSERDETAILS`(IN v_uid VARCHAR(255))
BEGIN

    SELECT UID, DISPLYID ,USR_FNAME, USR_LNAME, EMAIL, ROLEID, CREATED_DATE, LAST_MODIFIED_DATE
    FROM MUGENJO.TBL_USERS
    WHERE UID = v_uid;
	
END;
