USE mugenjo;

CREATE TABLE `tbl_db_log` (
  `LOGID` int(11) NOT NULL,
  `OBJECTNAME` varchar(255) DEFAULT NULL,
  `ERRORCODE` int(11) DEFAULT NULL,
  `ERRORDESCRIPTION` varchar(1000) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`LOGID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


insert into `tbl_db_log`(`LOGID`,`OBJECTNAME`,`ERRORCODE`,`ERRORDESCRIPTION`,`CREATED_DATE`) values (0,'PKG_MANAGEUSER.PRC_UPDATEUSER',1048,'Column ''DISPLYID'' cannot be null','2017-01-26 13:46:31');
insert into `tbl_db_log`(`LOGID`,`OBJECTNAME`,`ERRORCODE`,`ERRORDESCRIPTION`,`CREATED_DATE`) values (1,'PKG_MANAGEUSER.PRC_UPDATEUSER',1048,'Column ''DISPLYID'' cannot be null','2017-01-26 14:02:02');
insert into `tbl_db_log`(`LOGID`,`OBJECTNAME`,`ERRORCODE`,`ERRORDESCRIPTION`,`CREATED_DATE`) values (2,'PKG_MANAGEUSER.PRC_UPDATEUSER',1048,'Column ''DISPLYID'' cannot be null','2017-01-26 14:02:13');
